# -*- coding: utf-8 -*-
"""Conditional Statements (Assignment).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5geyTJybW-9_mmAf5cYZGym9wflnCv0

1) A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years.
Ask user for their salary and year of service and print the net bonus amount.
"""

salary = float(input("Enter salary: "))
years_serv = int(input("Enter the years: "))

if years_serv > 5:
    bonus_percentage = 5
    bonus_amount = (bonus_percentage / 100) * salary
    print("Your bonus amount is: $", bonus_amount)
else:
    print("No bonus!")

"""
2) Write a program to check whether a person is eligible for voting or not. (accept age from user) if age is greater than 17 eligible otherwise not eligible"""

age = int(input("Please enter your age: "))

if age > 17:
    print("You are eligible to vote!")
else:
    print("You are not eligible to vote")

"""
3) Write a program to check whether a number entered by user is even or odd."""

number = int(input("Please enter a number: "))

if number % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

"""4) Write a program to check whether a number is divisible by 7 or not.
Show Answer
"""

number = int(input("Please enter a number: "))

if number % 7 == 0:
    print("The number is divisible by 7")
else:
    print("The number is not divisible by 7")

"""5) Write a program to display
"Hello" if a number entered by user is a multiple of five , otherwise print "Bye".
"""

number = int(input("Please enter a number: "))

if number % 5 == 0:
    print("Hello")
else:
    print("Bye")

"""7) Write a program to display the last digit of a number.

"""

number = input("Please enter a number: ")

last_digit = int(number[-1])
print("The last digit of the number is:", last_digit)

"""9) Take values of length and breadth of a rectangle from user and print if it is square or rectangle."""

length = float(input("Please enter the length: "))
breadth = float(input("Please enter the breadth: "))

if length == breadth:
    print("It is a square")
else:
    print("It is a rectangle")

"""10) Take two int values from user and print greatest among them."""

first_number = int(input("Please enter the number: "))
second_number = int(input("Please enter the number: "))

if first_number > second_number:
    print("The greatest number is:", first_number)
else:
    print("The greatest number is:", second_number)

"""11) A shop will give discount of 10% if the cost of purchased quantity is more than 1000.
Ask user for quantity
Suppose, one unit will cost 100.
Judge and print total cost for user.
"""

quantity = int(input("Please enter the quantity: "))
costper_unit = 100
tot_cost = quantity * costper_unit

if tot_cost > 1000:
    discount = tot_cost * 0.1
    tot_cost -= discount

print("The total cost is:", tot_cost)

"""12) A school has following rules for grading system:

a. Below 25 - F

b. 25 to 45 - E

c. 45 to 50 - D

d. 50 to 60 - C

e. 60 to 80 - B

f. Above 80 - A

Ask user to enter marks and print the corresponding grade.
"""

marks = float(input("Please enter your marks: "))

if marks < 25:
    grade = 'F'
elif marks >= 25 and marks < 45:
    grade = 'E'
elif marks >= 45 and marks < 50:
    grade = 'D'
elif marks >= 50 and marks < 60:
    grade = 'C'
elif marks >= 60 and marks < 80:
    grade = 'B'
elif marks >= 80:
    grade = 'A'

print("Your grade is: ", grade)

"""14)A student will not be allowed to sit in exam if his/her attendence is less than 75%.

Take following input from user

Number of classes held

Number of classes attended.

And print

percentage of class attended

Is student is allowed to sit in exam or not.

"""

class_held = int(input("Enter the total number of classes held: "))
class_attended = int(input("Enter the number of classes you attended: "))
percentage = (class_attended / class_held) * 100

print("Your attendance percentage is:", percentage)

if percentage >= 75:
    print("You are allowed to sit in the exam.")
else:
    print("You are not allowed to sit in the exam due to low attendance.")

"""15) Modify the above question to allow student to sit if he/she has medical cause. Ask user if he/she has medical cause or not ( 'Y' or 'N' ) and print accordingly."""

class_held = int(input("Enter the total number of classes held: "))
class_attended = int(input("Enter the number of classes you attended: "))
percentage = (class_attended / class_held) * 100

print("Your attendance percentage is:", percentage)

medical_cause = input("Do you have a medical cause? (Y/N): ")

if percentage >= 75 or medical_cause == 'Y':
    if medical_cause == 'Y':
        print("You are allowed to sit in the exam due to a medical cause")
    else:
        print("You are allowed to sit in the exam")
else:
    print("You are not allowed to sit in the exam due to low attendance")

"""16) Write a program to check if a year is leap year or not.

If a year is divisible by 4 then it is leap year but if the year is century year like 2000, 1900, 2100 then it must be divisible by 400.
"""

year = int(input("Enter year: "))

if (year % 400 == 0):
    print(f"{year} is a leap year.")
elif (year % 100 == 0):
    print(f"{year} is not a leap year.")
elif (year % 4 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

"""17) Ask user to enter age, gender ( M or F ), marital status ( Y or N ) and then using following rules print their place of service.

if employee is female, then she will work only in urban areas.

if employee is a male and age is in between 20 to 40 then he may work in anywhere

if employee is male and age is in between 40 t0 60 then he will work in urban areas only.

And any other input of age should print "ERROR"
"""

age = int(input("Enter your age: "))
gender = input("Enter your gender (M or F): ")
marital_status = input("Enter your marital status (Y or N): ")

if gender == 'F':
    print("You will work only in urban areas")
elif gender == 'M':
    if 20 <= age <= 40:
        print("You may work anywhere")
    elif 40 < age <= 60:
        print("You will work in urban areas only")
    else:
        print("ERROR")
else:
    print("ERROR")

"""6) Write a program to calculate the electricity bill (accept number of unit from user) according to the following criteria :
     Unit                                                     Price  
uptp 100 units                                             no charge
Next 200 units                                              Rs 5 per unit
After 200 units                                             Rs 10 per unit
(For example if input unit is 350 than total bill amount is Rs.3500
(For example if input unit is 97 than total bill amount is Rs.0
(For example if input unit is 150 than total bill amount is Rs.750
"""

units = int(input("Enter the number of units: "))

if units <= 100:
    amount = 0
elif units <= 300:
    amount = (units - 100) * 5
else:
    amount = 1000 + (units - 300) * 10

print("Total electricity bill amount is Rs.", amount)

"""13) Take input of age of 3 people by user and determine oldest and youngest among them."""

age1 = int(input("Enter the age: "))
age2 = int(input("Enter the age: "))
age3 = int(input("Enter the age: "))

oldest = youngest = age1

if age2 > oldest:
    oldest = age2
if age3 > oldest:
    oldest = age3

if age2 < youngest:
    youngest = age2
if age3 < youngest:
    youngest = age3

print("The oldest person is", oldest, "years old")
print("The youngest person is", youngest, "years old")

